const KEY="regency-seasons-dev-v2"; const OLD_KEY="regency-season-dev-v1";
const DATA={stations:["The Glittering Heiress/Heir","The Destitute Noble","The Second Son or Daughter","The Mysterious Outsider","The Scandal-Touched Debut","The Brooding Widower/Widow"],memories:["A Secret Love Left Behind","A Family Scandal","A Childhood Friendship","A Sudden Loss","A Forbidden Education","A Whispered Rumour"],skills:["Graceful Dancing","Cutting Wit","Conversational Charm","Musical Talent","Horseback Riding","Gossipmongering at Teas","Needlework & Embroidery","Boldness Beyond Decorum","Duelling","Persuasive Letter-Writing","Grace","Poise","Wit","Composure","Courage","Empathy","Discretion"],resources:["A Stately Family Estate","A Substantial Dowry or Inheritance","A Fashionable Wardrobe of Parisian Silks","A Loyal Maid or Valet","An Invitation to Almack’s","A Prominent Family Name","A Handsome Carriage & Horses","A Collection of Love Letters","A Well-Placed Family Friend in Parliament","A Secret Garden or Country Retreat"],characters:["A Doting Parent with High Expectations","A Stern Aunt Who Guards the Family Honour","A Charming Suitor of Dubious Fortune","A Rival Debutante with Perfect Curls","A Meddlesome Sibling Eager to Upstage You","A Widowed Duke in Search of Companionship","A Gossip Columnist with a Sharp Quill","A Military Officer Returned from the Wars","A Governess Who Knows Too Much of Your Past","A Childhood Friend, Changed by Time Abroad"],marks:["A Scandalous Rumour","A Ruined Engagement","A Striking Scar","An Illegitimate Birth","An Infamous Flirtation","A Secret Debt Hanging Over Your Family","An Improper Hobby","A Disgraced Relative Who Casts a Shadow","A Reputation for Coldness (or Excessive Passion)","A Hidden Love That Must Never Be Known"]};
function fresh(){return{screen:"welcome",name:"",station:"",before:"",skills:[],resources:[],characters:[],marks:[],prompt:1,progress:{},journal:[],keywords:{},selectedKeywords:[],selectedSkill:null,outcome:null,draft:"",lastRoll:null,exhaustedSkills:[],activeMemories:[],pendingExperience:null,lastChanges:[],characterStates:{},quietUsed:false,refreshCredits:0,gentleTriggered:[],effectDone:false,spentResources:[],lostCharacters:[]}}
let db={slots:[null,null],active:null};let s=null;let view="home";
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&saved.slots)db=saved;else{const old=JSON.parse(localStorage.getItem(OLD_KEY));if(old&&old.name){db.slots[0]=old;db.active=0}}}catch{}
if(db.active!==null&&db.slots[db.active])s=db.slots[db.active];
const app=document.getElementById("app");
function normalise(){if(!s)return;s.exhaustedSkills=s.exhaustedSkills||[];s.activeMemories=s.activeMemories||[];s.characterStates=s.characterStates||{};s.quietUsed=!!s.quietUsed;s.refreshCredits=s.refreshCredits||0;s.gentleTriggered=s.gentleTriggered||[];s.spentResources=s.spentResources||[];s.lostCharacters=s.lostCharacters||[];s.characters.forEach(x=>{if(!s.characterStates[x])s.characterStates[x]="Neutral"})}
function save(){normalise();if(s&&db.active!==null)db.slots[db.active]=s;localStorage.setItem(KEY,JSON.stringify(db))}
function shell(body,nav=true){const navHtml=nav&&s?'<nav class="nav"><button onclick="goView(\'play\')">PLAY</button><button onclick="goView(\'character\')">CHARACTER</button><button onclick="goView(\'memories\')">MEMORIES</button><button onclick="goView(\'journal\')">JOURNAL</button></nav>':'';return '<div class="app"><header class="top"><button class="brand homebrand" onclick="home()">REGENCY: THE SEASON</button><div class="dev">'+(s?esc(s.name):"DEVELOPMENT BUILD")+'</div></header><main>'+body+'</main>'+navHtml+'</div>'}
function home(){save();view="home";render()}
function goView(x){save();view=x;render()}
function go(x){if(!s)return;s.screen=x;save();view="play";render()}
function random(a){return a[Math.floor(Math.random()*a.length)]}
function selectOptions(arr,val){return '<option value="">Choose…</option>'+arr.map(x=>'<option '+(x===val?'selected':'')+'>'+x+'</option>').join("")+'<option value="__own">Write my own…</option>'}
function welcome(){return homeView()}
function homeView(){const cards=db.slots.map((slot,i)=>slot?'<div class="card"><div class="eyebrow">Season '+(i+1)+'</div><h2>'+esc(slot.name)+'</h2><p>'+esc(slot.station||"")+'</p><p class="small">Prompt '+(slot.prompt||1)+' · '+standingFor(slot.marks||[])+'</p><button class="btn primary" onclick="openSlot('+i+')">Continue '+esc(slot.name)+'’s Season</button><button class="btn soft" onclick="openSection('+i+',\'journal\')">Read '+esc(slot.name)+'’s Journal</button><button class="btn soft" onclick="deleteSeason('+i+')">Delete Season</button></div>':'<div class="card"><div class="eyebrow">Season '+(i+1)+'</div><h2>An empty place in Society</h2><p class="small">Begin a separate character and Season.</p><button class="btn" onclick="newSeason('+i+')">Start a New Season</button></div>').join("");return shell('<div class="eyebrow">Mogshade Games</div><h1>Regency:<br>The Season</h1><p class="lede">Choose whose Season you wish to enter.</p>'+cards,false)}
function standingFor(marks){const n=marks.length;return n>=10?"Ruined":n>=7?"Notorious":n>=4?"Whispered About":"Unblemished"}
function openSlot(i){db.active=i;s=db.slots[i];normalise();view="play";save();render()}
function openSection(i,x){db.active=i;s=db.slots[i];view=x;save();render()}
function newSeason(i){db.active=i;s=fresh();s.screen="create";db.slots[i]=s;view="play";save();render()}
function deleteSeason(i){const slot=db.slots[i];if(!slot)return;const name=slot.name||"this character";if(!confirm("Delete "+name+"’s Season? This removes the character, journal and memories from this device."))return;db.slots[i]=null;if(db.active===i){db.active=null;s=null}localStorage.setItem(KEY,JSON.stringify(db));view="home";render()}
function pick(field,i,v){if(v==="__own"){v=prompt("Write your own:")||""} if(i==null)s[field]=v;else s[field][i]=v;save();render()}
function suggest(field,i,arr){pick(field,i,random(arr))}
function randomCharacter(){s.station=random(DATA.stations);s.before=random(DATA.memories);s.skills=shuffle(DATA.skills).slice(0,3);s.resources=shuffle(DATA.resources).slice(0,3);s.characters=shuffle(DATA.characters).slice(0,3);s.marks=[random(DATA.marks)];save();render()}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b}
function create(){for(const f of ["skills","resources","characters"])while(s[f].length<3)s[f].push("");return shell('<div class="eyebrow">Entering the Season</div><h2>Create your character</h2><p>Choose each part of your character, or generate a complete character at random. Nothing here is locked until you enter the Season.</p><button class="btn" onclick="randomCharacter()">Random Character</button><div class="card"><label>Your Name</label><input value="'+esc(s.name)+'" oninput="s.name=this.value;save()" placeholder="Your name"><label>Station</label><select onchange="pick(\'station\',null,this.value)">'+selectOptions(DATA.stations,s.station)+'</select><button class="btn soft" onclick="suggest(\'station\',null,DATA.stations)">Suggest</button><label>Memory Before the Season</label><select onchange="pick(\'before\',null,this.value)">'+selectOptions(DATA.memories,s.before)+'</select><button class="btn soft" onclick="suggest(\'before\',null,DATA.memories)">Suggest</button></div>'+multi("Three Skills","skills",DATA.skills)+multi("Three Resources","resources",DATA.resources)+multi("Three Characters","characters",DATA.characters)+'<div class="card"><label>Your first Mark</label><select onchange="pick(\'marks\',0,this.value)">'+selectOptions(DATA.marks,s.marks[0]||"")+'</select><button class="btn soft" onclick="suggest(\'marks\',0,DATA.marks)">Suggest</button></div><button class="btn primary" onclick="enterSeason()">Enter the Season</button>',false)}
function multi(title,field,arr){return '<div class="card"><h3>'+title+'</h3>'+[0,1,2].map(i=>'<select onchange="pick(\''+field+'\','+i+',this.value)">'+selectOptions(arr,s[field][i])+'</select><button class="btn soft" onclick="suggest(\''+field+'\','+i+',DATA.'+field+')">Suggest</button>').join("")+'</div>'}
function enterSeason(){if(!s.name||!s.station||!s.before||s.skills.some(x=>!x)||s.resources.some(x=>!x)||s.characters.some(x=>!x)||!s.marks[0]){alert("Complete each part of your character first.");return}if(!s.activeMemories||!s.activeMemories.length)s.activeMemories=[{title:s.before,experiences:[]}];s.screen="prompt";save();view="play";render()}
function current(){return REGENCY_PROMPTS[s.prompt-1]} function stageIndex(){return Math.min(s.progress[s.prompt]||0,2)}
function promptView(){normalise();const p=current(),i=stageIndex(),st=p.stages[i],seen=p.keywords.filter(k=>s.keywords[k]);const skills=s.skills.map(x=>{const used=s.exhaustedSkills.includes(x);return '<button class="btn '+(s.selectedSkill===x?'primary':'')+'" '+(used?'disabled':'')+' onclick="chooseSkill(\''+escq(x)+'\')">'+esc(x)+(used?' · Checked':'')+'</button>'}).join("");const resources=s.resources.filter(x=>!s.spentResources.includes(x)).map(x=>'<button class="btn soft" onclick="spendForSuccess(\''+escq(x)+'\')">'+esc(x)+'</button>').join("");return shell('<div class="eyebrow">Prompt '+p.n+' · Stage '+(i+1)+'</div><h2>'+p.title+'</h2><div class="card quote">'+p.intro+'</div><div class="stage">'+st[0]+'</div><p>'+st[1]+'</p><div class="effect"><strong>Effect</strong><br>'+st[2]+'</div><p class="write"><strong>Write:</strong> '+st[3]+'</p><h3>How do you meet the requirement?</h3><p class="small">Choose an available Skill when appropriate. You may also spend a fitting Resource as fictional leverage, use another permitted route, or choose Failure.</p>'+skills+(resources?'<details><summary>Spend a Resource / Polite Substitution</summary>'+resources+'</details>':'')+'<button class="btn '+(s.outcome==="success"&&!s.selectedSkill?'primary':'')+'" onclick="otherSuccess()">Success — another permitted route</button><button class="btn '+(s.outcome==="failure"?'primary':'')+'" onclick="failure()">Choose Failure</button><h3>Your Experience</h3><textarea id="draft" oninput="s.draft=this.value;save()" placeholder="Write or dictate your Experience…">'+esc(s.draft)+'</textarea><button id="dictateBtn" class="btn" onclick="dictate()">🎙 Start Dictation</button><button id="flourishBtn" class="btn soft" onclick="flourish()">✨ Flourish</button><span id="speechStatus" class="small"></span><div id="flourishStatus" class="small"></div><div class="tagrow"><span class="small">Story threads:</span>'+p.keywords.map(k=>'<button class="pill '+(s.selectedKeywords.includes(k)?'selected ':'')+(s.keywords[k]?'seen':'')+'" onclick="toggleKeyword(\''+escq(k)+'\')">'+k+(s.keywords[k]?' · '+s.keywords[k]:'')+'</button>').join("")+'</div>'+(seen.length?'<div class="notice good">A thread returns: '+seen.join(", ")+'. A reminder, never a requirement.</div>':'')+'<button class="btn primary" onclick="resolveStage()">Record Experience</button>')}
function chooseSkill(x){if((s.exhaustedSkills||[]).includes(x))return;s.selectedSkill=x;s.outcome="success";save();render()} function otherSuccess(){s.selectedSkill=null;s.outcome="success";save();render()} function failure(){s.selectedSkill=null;s.outcome="failure";save();render()}
function spendForSuccess(x){if(!s.resources.includes(x)||s.spentResources.includes(x))return;s.spentResources.push(x);s.outcome="success";s.selectedSkill=null;s.lastChanges=(s.lastChanges||[]).concat(x+" was spent.");save();render()}
function toggleKeyword(k){const a=s.selectedKeywords,i=a.indexOf(k);i>=0?a.splice(i,1):a.push(k);save();render()}
function resolveStage(){if(!s.outcome){alert("Choose how you resolve the requirement first.");return}if(!s.draft.trim()){alert("Write or dictate your Experience first.");return}const p=current(),i=stageIndex();const entry={prompt:p.n,title:p.title,stage:i+1,text:s.draft.trim(),keywords:[...s.selectedKeywords],outcome:s.outcome,skill:s.selectedSkill};s.journal.push(entry);s.pendingExperience=entry;s.lastChanges=[];if(s.selectedSkill){s.exhaustedSkills=s.exhaustedSkills||[];if(!s.exhaustedSkills.includes(s.selectedSkill))s.exhaustedSkills.push(s.selectedSkill);s.lastChanges.push(s.selectedSkill+" has been checked and is now exhausted.");}s.selectedKeywords.forEach(k=>s.keywords[k]=(s.keywords[k]||0)+1);s.progress[p.n]=(s.progress[p.n]||0)+1;s.draft="";s.selectedKeywords=[];s.selectedSkill=null;s.outcome=null;s.screen="effects";s.effectDone=false;save();render()}
function effectsView(){const e=s.pendingExperience;if(!e){s.screen="memory";return memoryView()}const effect=current().stages[Math.min(e.stage-1,2)][2];return shell('<div class="eyebrow">Resolve the Prompt</div><h2>What changed?</h2>'+(s.lastChanges.length?'<div class="notice good">'+s.lastChanges.map(esc).join("<br>")+'</div>':'')+'<div class="effect"><strong>Resolve these Effects in the order written</strong><br>'+effect+'</div><p class="small">The app tracks common gains and losses below. Where the Prompt gives a choice, you still make it.</p>'+effectActions(effect)+'<button class="btn primary" onclick="effectsComplete()">Effects resolved → Memory</button>')}
function effectActions(t){let h="";const gains=[...t.matchAll(/gain 1 Resource \(([^)]+)\)/gi)];gains.forEach(m=>{if(!s.resources.includes(m[1]))h+='<button class="btn" onclick="gainResource(\''+escq(m[1])+'\')">+ Resource: '+esc(m[1])+'</button>'});const marks=[...t.matchAll(/gain 1 Mark \(([^)]+)\)/gi)];marks.forEach(m=>{if(!s.marks.includes(m[1]))h+='<button class="btn" onclick="gainMark(\''+escq(m[1])+'\')">+ Mark: '+esc(m[1])+'</button>'});const chars=[...t.matchAll(/(?:Create|gain) (?:a |1 )?Character \(([^)]+)\)/gi)];chars.forEach(m=>{if(!s.characters.includes(m[1]))h+='<button class="btn" onclick="gainCharacter(\''+escq(m[1])+'\')">+ Character: '+esc(m[1])+'</button>'});if(/Transform Skill/i.test(t))h+='<button class="btn" onclick="transformSkill()">Transform a Skill</button>';if(/Lose 1 Resource/i.test(t))h+='<button class="btn" onclick="loseResource()">Lose a Resource</button>';return h||'<div class="notice">Read the Effect above and make any choice it asks of you.</div>'}
function gainResource(x){normalise();if(standingFor(s.marks)==="Notorious"){if(!confirm("You are Notorious. Accept "+x+" and gain 1 Mark? Cancel refuses the Resource."))return;gainMark("Resource accepted while Notorious")}s.resources.push(x);s.lastChanges.push("Gained Resource: "+x);save();render()}
function gainMark(x){s.marks.push(x);s.lastChanges.push("Gained Mark: "+x);s.refreshCredits++;[3,6,9].forEach(n=>{if(s.marks.length>=n&&!s.gentleTriggered.includes(n)){s.gentleTriggered.push(n);s.lastChanges.push("Gentle Consequence triggered at "+n+" Marks — resolve it from the Character screen.")}});if(s.marks.length>=10)s.screen="ruined";save();render()}
function gainCharacter(x){s.characters.push(x);s.characterStates[x]="Neutral";s.lastChanges.push("Created Character: "+x);save();render()}
function loseResource(){const live=s.resources.filter(x=>!s.spentResources.includes(x));if(!live.length)return;const x=prompt("Type the Resource to lose exactly:\n"+live.join("\n"));if(live.includes(x)){s.spentResources.push(x);s.lastChanges.push("Lost Resource: "+x);save();render()}}
function transformSkill(){const from=prompt("Which Skill changes?\n"+s.skills.join("\n"));if(!s.skills.includes(from))return;const to=prompt("What does it become?");if(!to)return;const i=s.skills.indexOf(from);s.skills[i]=to;s.exhaustedSkills=s.exhaustedSkills.filter(x=>x!==from);s.lastChanges.push("Transformed Skill: "+from+" → "+to);save();render()}
function effectsComplete(){s.effectDone=true;s.screen="memory";save();render()}
function memoryView(){const e=s.pendingExperience;if(!e){s.screen="between";save();return betweenView()}s.activeMemories=s.activeMemories||[{title:s.before,experiences:[]}];return shell('<div class="eyebrow">Memory Management</div><h2>Where does this belong?</h2><p class="small">Place the Experience beneath an active Memory, or begin a new one. Each Memory holds up to three Experiences.</p>'+s.activeMemories.map((m,i)=>'<button class="btn choice" '+(m.experiences.length>=3?'disabled':'')+' onclick="placeMemory('+i+')"><strong>'+esc(m.title)+'</strong><br><span class="small">'+m.experiences.length+' of 3 Experiences</span></button>').join("")+'<button class="btn primary choice" onclick="newMemory()">+ Begin a new Memory</button>')}
function placeMemory(i){const m=s.activeMemories[i];if(m.experiences.length>=3)return;m.experiences.push(s.pendingExperience);finishMemory()}
function newMemory(){if(s.activeMemories.length>=5){s.screen="strikeMemory";save();render();return}const suggested=(s.pendingExperience.keywords&&s.pendingExperience.keywords[0])||s.pendingExperience.title;const title=prompt("Name this Memory:",suggested)||suggested;s.activeMemories.push({title,experiences:[s.pendingExperience]});s.refreshCredits++;s.lastChanges.push("Created Memory: "+title+". You may refresh one Skill.");finishMemory()}
function strikeMemoryView(){return shell('<div class="eyebrow">Five Active Memories</div><h2>Something must make way.</h2><p>Strike one active Memory and all its Experiences to create the new one. Striking a Memory also lets you refresh one Skill.</p>'+s.activeMemories.map((m,i)=>'<button class="btn choice" onclick="strikeMemory('+i+')">'+esc(m.title)+' <span class="small">'+m.experiences.length+'/3</span></button>').join("")+'<button class="btn soft" onclick="go(\'memory\')">Keep my current Memories</button>')}
function strikeMemory(i){const old=s.activeMemories.splice(i,1)[0];s.refreshCredits++;s.lastChanges.push("Struck Memory: "+old.title+". You may refresh one Skill.");s.screen="memory";save();render()}
function finishMemory(){s.pendingExperience=null;s.screen=s.refreshCredits>0?"refresh":"between";save();render()}
function refreshView(){const checked=s.exhaustedSkills||[];if(!s.refreshCredits||!checked.length){s.refreshCredits=0;s.screen="between";save();return betweenView()}return shell('<div class="eyebrow">Refresh a Skill</div><h2>Society has changed you.</h2><p>You have '+s.refreshCredits+' refresh '+(s.refreshCredits===1?'opportunity':'opportunities')+'. Choose an exhausted Skill.</p>'+checked.map(x=>'<button class="btn choice" onclick="refreshSkill(\''+escq(x)+'\')">'+esc(x)+'</button>').join("")+'<button class="btn soft" onclick="skipRefresh()">Continue without using the remaining refresh</button>')}
function refreshSkill(x){s.exhaustedSkills=s.exhaustedSkills.filter(y=>y!==x);s.refreshCredits--;s.lastChanges.push("Refreshed Skill: "+x);if(!s.refreshCredits||!s.exhaustedSkills.length)s.screen="between";save();render()}
function skipRefresh(){s.refreshCredits=0;s.screen="between";save();render()}
function betweenView(){return shell('<div class="eyebrow">Between Prompts</div><h2>A little room to breathe.</h2><p>Before the dice turn again, you may take one Quiet Moment.</p>'+(!s.quietUsed?'<button class="btn" onclick="startQuiet()">Take a Quiet Moment</button>':'<div class="notice">Quiet Moment used for this interval.</div>')+(s.characters.filter(x=>!s.lostCharacters.includes(x)).length>=3&&s.marks.length?'<button class="btn soft" onclick="sundering()">Quiet Sundering of Ties</button>':'')+'<button class="btn primary" onclick="toDice()">Continue to the dice →</button>')}
function startQuiet(){s.screen="quiet";s.quietDraft="";save();render()}
function quietView(){return shell('<div class="eyebrow">Quiet Moment</div><h2>Write the moment between.</h2><textarea oninput="s.quietDraft=this.value;save()" placeholder="A walk, a private conversation, a letter, tea…">'+esc(s.quietDraft||"")+'</textarea><p>Then choose one:</p><button class="btn" onclick="quietRefresh()">Refresh one Skill</button><button class="btn" onclick="quietRelationship()">Change one Character relationship</button>')}
function recordQuiet(){if((s.quietDraft||"").trim())s.journal.push({prompt:"—",stage:"Quiet Moment",title:"Quiet Moment",text:s.quietDraft.trim(),keywords:[]});s.quietUsed=true;s.quietDraft="";save()}
function quietRefresh(){recordQuiet();s.refreshCredits++;s.screen="refresh";save();render()}
function quietRelationship(){const live=s.characters.filter(x=>!s.lostCharacters.includes(x));const who=prompt("Which Character?\n"+live.join("\n"));if(!live.includes(who))return;const status=prompt("New status: Ally, Neutral, Rival, Admirer, or Distant",s.characterStates[who]||"Neutral");if(!["Ally","Neutral","Rival","Admirer","Distant"].includes(status))return;recordQuiet();s.characterStates[who]=status;if(status==="Admirer"&&!s.resources.includes("Devotion"))s.resources.push("Devotion");s.screen="between";save();render()}
function sundering(){const live=s.characters.filter(x=>!s.lostCharacters.includes(x));const names=prompt("Type three Character names separated by |\n"+live.join("\n"));if(!names)return;const chosen=names.split("|").map(x=>x.trim());if(chosen.length!==3||new Set(chosen).size!==3||chosen.some(x=>!live.includes(x)))return;s.lostCharacters.push(...chosen);if(s.marks.length)s.marks.pop();s.lastChanges.push("Quiet Sundering: three Characters lost; removed one Mark.");save();render()}
function toDice(){s.quietUsed=false;s.screen="dice";save();render()}
function ruinedView(){return shell('<div class="eyebrow">Ruined</div><h2>Your Season ends here.</h2><p>You have reached 10 Marks. The Core Rules now send the character to the Final Reflection.</p><button class="btn" onclick="goView(\'journal\')">Read the Journal</button>')}
function dice(){const l=s.lastRoll;return shell('<div class="eyebrow">The Season turns</div><h2>Roll the dice</h2><p>Both dice are rolled together. One roll decides where the Season carries you next.</p><div class="grid2"><div class="dice">d10<br><strong>'+(l?l.d10:"—")+'</strong></div><div class="dice">d6<br><strong>'+(l?l.d6:"—")+'</strong></div></div>'+(!l?'<button class="btn primary" onclick="roll()">Roll both dice</button>':'<div class="notice"><strong>'+l.message+'</strong></div><button class="btn primary" onclick="continueRoll()">Continue →</button>'))}
function roll(){if(s.lastRoll)return;move(1+Math.floor(Math.random()*10),1+Math.floor(Math.random()*6))}
function move(a,b){let msg;if(a===b){if((s.progress[s.prompt]||0)<3)msg="Doubles. Remain on Prompt "+s.prompt+" and advance to its next Stage.";else msg="Doubles, but all three Stages here are complete. Choose one Prompt forward or backward."}else{const d=Math.abs(a-b),dir=b<a?1:-1,target=s.prompt+dir*d,clamped=Math.max(1,Math.min(10,target));s.prompt=clamped;msg=(dir>0?"Move forward ":"Move backward ")+d+" Prompt"+(d===1?"":"s")+". "+(target!==clamped?"This development slice stops at Prompt "+clamped+".":"You arrive at Prompt "+clamped+".")}s.lastRoll={d10:a,d6:b,message:msg};save();render()}
function continueRoll(){if(s.lastRoll&&s.lastRoll.d10===s.lastRoll.d6&&(s.progress[s.prompt]||0)>=3){s.screen="edge";save();render();return}s.lastRoll=null;s.screen="prompt";save();render()}
function edge(){return shell('<div class="eyebrow">Completed Prompt</div><h2>All three Stages are complete.</h2><p>The rules let you move one Prompt forward or backward.</p><button class="btn" onclick="edgeMove(-1)">← Back one</button><button class="btn primary" onclick="edgeMove(1)">Forward one →</button>')}
function edgeMove(n){s.prompt=Math.max(1,Math.min(10,s.prompt+n));s.lastRoll=null;s.screen="prompt";save();render()}
function characterView(){normalise();const marks=s.marks.length;const liveRes=s.resources.filter(x=>!s.spentResources.includes(x));return shell('<div class="eyebrow">Character Sheet</div><h2>'+esc(s.name)+'</h2><div class="statusline"><span>'+esc(s.station)+'</span><span>'+marks+' Mark'+(marks===1?"":"s")+'</span><span>'+standingFor(s.marks)+'</span></div><div class="card"><h3>Skills</h3>'+s.skills.map(x=>'<p>'+esc(x)+(s.exhaustedSkills.includes(x)?' <strong>✓ Checked</strong>':' <span class="small">Available</span>')+'</p>').join("")+'<h3>Resources</h3><p>'+(liveRes.length?liveRes.map(esc).join(" · "):"None currently available")+'</p><h3>Characters</h3>'+s.characters.map(x=>'<p class="'+(s.lostCharacters.includes(x)?'small':'')+'">'+esc(x)+' · <strong>'+(s.lostCharacters.includes(x)?'Lost':esc(s.characterStates[x]||"Neutral"))+'</strong></p>').join("")+'<h3>Marks</h3><p>'+s.marks.map(esc).join(" · ")+'</p></div>'+(s.gentleTriggered.length?'<div class="notice"><strong>Gentle Consequence thresholds reached:</strong> '+s.gentleTriggered.join(", ")+' Marks. These choices still need resolving in this development build.</div>':''))}
function memoriesView(){const mems=s.activeMemories||[{title:s.before,experiences:[]}];return shell('<div class="eyebrow">'+esc(s.name)+'’s Season</div><h2>Memories</h2><p class="small">The active Memories shaping this Season.</p>'+mems.map(m=>'<div class="card"><strong>'+esc(m.title)+'</strong><div class="small">'+m.experiences.length+' of 3 Experiences</div>'+m.experiences.map(e=>'<p>'+esc(e.text)+'</p>').join("")+'</div>').join("")+'<h3>Keyword threads</h3><div class="tagrow">'+Object.entries(s.keywords||{}).map(([k,v])=>'<span class="pill seen">'+esc(k)+' · '+v+'</span>').join("")+'</div>')}
function journalView(){return shell('<div class="eyebrow">'+esc(s.name)+'’s Season</div><h2>'+esc(s.name)+'’s Journal</h2><p class="small">The story as it has been written.</p>'+(s.journal.length?s.journal.map(j=>'<div class="journal-entry"><div class="small">Prompt '+j.prompt+' · Stage '+j.stage+'</div><strong>'+esc(j.title)+'</strong><p>'+esc(j.text)+'</p></div>').join(""):'<div class="card"><p>This journal is waiting for its first Experience.</p></div>')+'<div class="rule"></div><button class="btn soft" onclick="home()">Choose another Season</button>')}
function story(){return characterView()}
let activeRecognition=null;
function dictate(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition,el=document.getElementById("speechStatus"),btn=document.getElementById("dictateBtn");if(activeRecognition){activeRecognition.stop();return}if(!SR){el.textContent="Dictation is not available in this browser. You can keep typing normally.";return}const r=new SR();activeRecognition=r;r.lang="en-GB";r.interimResults=true;r.continuous=true;let committed=s.draft.trim();if(btn)btn.textContent="■ Stop Dictation";el.textContent="Listening… tap Stop Dictation when you are finished.";r.onresult=e=>{let finalText="";let interim="";for(let i=e.resultIndex;i<e.results.length;i++){const part=e.results[i][0].transcript.trim();if(e.results[i].isFinal)finalText+=(finalText?" ":"")+part;else interim+=(interim?" ":"")+part}if(finalText){finalText=finalText[0].toUpperCase()+finalText.slice(1);committed=(committed?committed+" ":"")+finalText;s.draft=committed;save()}const box=document.getElementById("draft");if(box)box.value=committed+(interim?(committed?" ":"")+interim:"")};r.onerror=e=>{if(e.error!=="no-speech")el.textContent="Dictation problem: "+e.error};r.onend=()=>{activeRecognition=null;const box=document.getElementById("draft");s.draft=committed;if(box)box.value=s.draft;save();if(btn)btn.textContent="🎙 Start Dictation";el.textContent=s.draft?"Dictation stopped. Tap Start Dictation to continue.":""};try{r.start()}catch{activeRecognition=null;if(btn)btn.textContent="🎙 Start Dictation";el.textContent="Dictation could not start."}}
async function flourish(){const box=document.getElementById("draft"),status=document.getElementById("flourishStatus"),btn=document.getElementById("flourishBtn");if(!s.draft.trim()){status.textContent="Write or dictate something first.";return}status.textContent="Giving your words a gentle polish…";if(btn)btn.disabled=true;try{const p=current(),i=stageIndex(),res=await fetch("/api/flourish",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:s.draft,prompt:p.title,stage:p.stages[i][0],keywords:p.keywords})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Flourish is not available yet.");if(data.text){s.draft=data.text;if(box)box.value=s.draft;save();status.textContent="Flourish applied. Your text is still fully editable."}}catch(e){status.textContent=e.message||"Flourish could not run."}finally{if(btn)btn.disabled=false}}
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function escq(x){return String(x).replace(/\\/g,"\\\\").replace(/'/g,"\\'")}
function playView(){if(!s)return homeView();normalise();return s.screen==="create"?create():s.screen==="prompt"?promptView():s.screen==="effects"?effectsView():s.screen==="memory"?memoryView():s.screen==="strikeMemory"?strikeMemoryView():s.screen==="refresh"?refreshView():s.screen==="between"?betweenView():s.screen==="quiet"?quietView():s.screen==="dice"?dice():s.screen==="edge"?edge():s.screen==="ruined"?ruinedView():promptView()}
function render(){let v;if(view==="home"||!s)v=homeView();else if(view==="character")v=characterView();else if(view==="memories")v=memoriesView();else if(view==="journal")v=journalView();else v=playView();app.innerHTML=v}render();