const KEY="regency-season-dev-v1";
const DATA={stations:["The Glittering Heiress/Heir","The Destitute Noble","The Second Son or Daughter","The Mysterious Outsider","The Scandal-Touched Debut","The Brooding Widower/Widow"],memories:["A Secret Love Left Behind","A Family Scandal","A Childhood Friendship","A Sudden Loss","A Forbidden Education","A Whispered Rumour"],skills:["Graceful Dancing","Cutting Wit","Conversational Charm","Musical Talent","Horseback Riding","Gossipmongering at Teas","Needlework & Embroidery","Boldness Beyond Decorum","Duelling","Persuasive Letter-Writing","Grace","Poise","Wit","Composure","Courage","Empathy","Discretion"],resources:["A Stately Family Estate","A Substantial Dowry or Inheritance","A Fashionable Wardrobe of Parisian Silks","A Loyal Maid or Valet","An Invitation to Almack’s","A Prominent Family Name","A Handsome Carriage & Horses","A Collection of Love Letters","A Well-Placed Family Friend in Parliament","A Secret Garden or Country Retreat"],characters:["A Doting Parent with High Expectations","A Stern Aunt Who Guards the Family Honour","A Charming Suitor of Dubious Fortune","A Rival Debutante with Perfect Curls","A Meddlesome Sibling Eager to Upstage You","A Widowed Duke in Search of Companionship","A Gossip Columnist with a Sharp Quill","A Military Officer Returned from the Wars","A Governess Who Knows Too Much of Your Past","A Childhood Friend, Changed by Time Abroad"],marks:["A Scandalous Rumour","A Ruined Engagement","A Striking Scar","An Illegitimate Birth","An Infamous Flirtation","A Secret Debt Hanging Over Your Family","An Improper Hobby","A Disgraced Relative Who Casts a Shadow","A Reputation for Coldness (or Excessive Passion)","A Hidden Love That Must Never Be Known"]};
function fresh(){return{screen:"welcome",name:"",station:"",before:"",skills:[],resources:[],characters:[],marks:[],prompt:1,progress:{},journal:[],keywords:{},selectedKeywords:[],selectedSkill:null,outcome:null,draft:"",lastRoll:null,exhaustedSkills:[],activeMemories:[],pendingExperience:null,lastChanges:[]}}
let s;try{s=JSON.parse(localStorage.getItem(KEY))||fresh()}catch{s=fresh()} const app=document.getElementById("app");
function save(){localStorage.setItem(KEY,JSON.stringify(s))}
function set(p,v){s[p]=v;save();render()}
function shell(body,nav=true){return '<div class="app"><header class="top"><div class="brand">REGENCY: THE SEASON</div><div class="dev">DEVELOPMENT BUILD</div></header><main>'+body+'</main>'+(nav&&s.screen!=="welcome"&&s.screen!=="create"?'<nav class="nav"><button onclick="go(\'prompt\')">JOURNAL</button><button onclick="go(\'dice\')">SEASON</button><button onclick="go(\'story\')">STORY</button></nav>':'')+'</div>'}
function go(x){s.screen=x;save();render()}
function random(a){return a[Math.floor(Math.random()*a.length)]}
function selectOptions(arr,val){return '<option value="">Choose…</option>'+arr.map(x=>'<option '+(x===val?'selected':'')+'>'+x+'</option>').join("")+'<option value="__own">Write my own…</option>'}
function welcome(){return shell('<div class="eyebrow">Mogshade Games</div><h1>Regency:<br>The Season</h1><p class="lede">A solo journalling storytelling game of romance, social intrigue, reputation, and scandal.</p><div class="card quote">“Solitude is merely society with better manners; bring a pen.”<br><span class="small">Lady Crackenthorpe</span></div><button class="btn primary" onclick="newSeason()">Begin New Season</button>'+(localStorage.getItem(KEY)&&s.name?'<button class="btn" onclick="go(\'prompt\')">Continue '+esc(s.name)+"’s Season</button>":''),false)}
function newSeason(){s=fresh();s.screen="create";save();render()}
function pick(field,i,v){if(v==="__own"){v=prompt("Write your own:")||""} if(i==null)s[field]=v;else s[field][i]=v;save();render()}
function suggest(field,i,arr){pick(field,i,random(arr))}
function create(){for(const f of ["skills","resources","characters"])while(s[f].length<3)s[f].push("");return shell('<div class="eyebrow">Entering the Season</div><h2>Create your character</h2><p>Choose, take a suggestion, or write your own. Nothing here is locked until you enter the Season.</p><div class="card"><label>Your Name</label><input value="'+esc(s.name)+'" oninput="s.name=this.value;save()" placeholder="Your name"><label>Station</label><select onchange="pick(\'station\',null,this.value)">'+selectOptions(DATA.stations,s.station)+'</select><button class="btn soft" onclick="suggest(\'station\',null,DATA.stations)">Suggest</button><label>Memory Before the Season</label><select onchange="pick(\'before\',null,this.value)">'+selectOptions(DATA.memories,s.before)+'</select><button class="btn soft" onclick="suggest(\'before\',null,DATA.memories)">Suggest</button></div>'+multi("Three Skills","skills",DATA.skills)+multi("Three Resources","resources",DATA.resources)+multi("Three Characters","characters",DATA.characters)+'<div class="card"><label>Your first Mark</label><select onchange="pick(\'marks\',0,this.value)">'+selectOptions(DATA.marks,s.marks[0]||"")+'</select><button class="btn soft" onclick="suggest(\'marks\',0,DATA.marks)">Suggest</button></div><button class="btn primary" onclick="enterSeason()">Enter the Season</button>',false)}
function multi(title,field,arr){return '<div class="card"><h3>'+title+'</h3>'+[0,1,2].map(i=>'<select onchange="pick(\''+field+'\','+i+',this.value)">'+selectOptions(arr,s[field][i])+'</select><button class="btn soft" onclick="suggest(\''+field+'\','+i+',DATA.'+field+')">Suggest</button>').join("")+'</div>'}
function enterSeason(){if(!s.name||!s.station||!s.before||s.skills.some(x=>!x)||s.resources.some(x=>!x)||s.characters.some(x=>!x)||!s.marks[0]){alert("Complete each part of your character first.");return}if(!s.activeMemories||!s.activeMemories.length)s.activeMemories=[{title:s.before,experiences:[]}];s.screen="prompt";save();render()}
function current(){return REGENCY_PROMPTS[s.prompt-1]} function stageIndex(){return Math.min(s.progress[s.prompt]||0,2)}
function promptView(){const p=current(),i=stageIndex(),st=p.stages[i];const seen=p.keywords.filter(k=>s.keywords[k]);return shell('<div class="eyebrow">Prompt '+p.n+' · Stage '+(i+1)+'</div><h2>'+p.title+'</h2><div class="tagrow">'+p.keywords.map(k=>'<button class="pill '+(s.selectedKeywords.includes(k)?'selected ':'')+(s.keywords[k]?'seen':'')+'" onclick="toggleKeyword(\''+escq(k)+'\')">'+k+(s.keywords[k]?' · '+s.keywords[k]:'')+'</button>').join("")+'</div>'+(seen.length?'<div class="notice good">A thread returns: '+seen.join(", ")+'. These are reminders, not requirements.</div>':'')+'<div class="card quote">'+p.intro+'</div><div class="stage">'+st[0]+'</div><p>'+st[1]+'</p><div class="effect"><strong>Effect</strong><br>'+st[2]+'</div><p class="write"><strong>Write:</strong> '+st[3]+'</p><div class="rule"></div><h3>How do you meet the requirement?</h3><p class="small">Choose a Skill if one fits. The prototype also lets you choose Success by another fictional route, or deliberately choose Failure.</p>'+s.skills.map(x=>'<button class="btn '+(s.selectedSkill===x?'primary':'')+'" onclick="chooseSkill(\''+escq(x)+'\')">'+x+'</button>').join("")+'<br><button class="btn '+(s.outcome==="success"&&!s.selectedSkill?'primary':'')+'" onclick="otherSuccess()">Success — Character, Resource or Memory</button><button class="btn '+(s.outcome==="failure"?'primary':'')+'" onclick="failure()">Choose Failure</button><h3>Your Experience</h3><textarea id="draft" oninput="s.draft=this.value;save()" placeholder="Write or dictate your Experience…">'+esc(s.draft)+'</textarea><button class="btn" onclick="dictate()">🎙 Dictate</button> <span id="speechStatus" class="small"></span><p class="small">Tap any Prompt Keywords above that mattered in what you wrote. The app will remember them as story threads.</p><button class="btn primary" onclick="resolveStage()">Record Experience</button>')}
function chooseSkill(x){s.selectedSkill=x;s.outcome="success";save();render()} function otherSuccess(){s.selectedSkill=null;s.outcome="success";save();render()} function failure(){s.selectedSkill=null;s.outcome="failure";save();render()}
function toggleKeyword(k){const a=s.selectedKeywords,i=a.indexOf(k);i>=0?a.splice(i,1):a.push(k);save();render()}
function resolveStage(){if(!s.outcome){alert("Choose how you resolve the requirement first.");return}if(!s.draft.trim()){alert("Write or dictate your Experience first.");return}const p=current(),i=stageIndex();const entry={prompt:p.n,title:p.title,stage:i+1,text:s.draft.trim(),keywords:[...s.selectedKeywords],outcome:s.outcome,skill:s.selectedSkill};s.journal.push(entry);s.pendingExperience=entry;s.lastChanges=[];if(s.selectedSkill){s.exhaustedSkills=s.exhaustedSkills||[];if(!s.exhaustedSkills.includes(s.selectedSkill))s.exhaustedSkills.push(s.selectedSkill);s.lastChanges.push(s.selectedSkill+" has been checked and is now exhausted.");}s.selectedKeywords.forEach(k=>s.keywords[k]=(s.keywords[k]||0)+1);s.progress[p.n]=(s.progress[p.n]||0)+1;s.draft="";s.selectedKeywords=[];s.selectedSkill=null;s.outcome=null;s.screen="memory";save();render()}
function memoryView(){const e=s.pendingExperience;if(!e){s.screen="dice";save();return dice()}s.activeMemories=s.activeMemories||[{title:s.before,experiences:[]}];return shell('<div class="eyebrow">Experience recorded</div><h2>What changed?</h2>'+(s.lastChanges.length?'<div class="notice good">'+s.lastChanges.map(esc).join("<br>")+'</div>':'<div class="notice">No Skill was checked for this Experience.</div>')+'<div class="effect"><strong>Prompt Effect</strong><br>'+current().stages[Math.min(e.stage-1,2)][2]+'</div><h3>Place this Experience</h3><p class="small">Every Experience belongs beneath an active Memory. Add it to one that already exists, or begin a new Memory from what just happened.</p>'+s.activeMemories.map((m,i)=>'<button class="btn choice" onclick="placeMemory('+i+')"><strong>'+esc(m.title)+'</strong><br><span class="small">'+m.experiences.length+' of 3 Experiences</span></button>').join("")+'<button class="btn primary choice" onclick="newMemory()">+ Begin a new Memory</button><div class="rule"></div><button class="btn soft" onclick="go(\'story\')">View Character Sheet & Memories</button>')}
function placeMemory(i){const m=s.activeMemories[i];if(m.experiences.length>=3){alert("That Memory already holds three Experiences.");return}m.experiences.push(s.pendingExperience);finishMemory()}
function newMemory(){if(s.activeMemories.length>=5){alert("You already have five active Memories. Memory management will be the next rules pass.");return}const suggested=(s.pendingExperience.keywords&&s.pendingExperience.keywords[0])||s.pendingExperience.title;const title=prompt("Name this Memory:",suggested)||suggested;s.activeMemories.push({title,experiences:[s.pendingExperience]});finishMemory()}
function finishMemory(){s.pendingExperience=null;s.screen="dice";save();render()}
function dice(){const l=s.lastRoll;return shell('<div class="eyebrow">The Season turns</div><h2>Roll the dice</h2><p>Both dice are rolled together. One roll decides where the Season carries you next.</p><div class="grid2"><div class="dice">d10<br><strong>'+(l?l.d10:"—")+'</strong></div><div class="dice">d6<br><strong>'+(l?l.d6:"—")+'</strong></div></div>'+(!l?'<button class="btn primary" onclick="roll()">Roll both dice</button>':'<div class="notice"><strong>'+l.message+'</strong></div><button class="btn primary" onclick="continueRoll()">Continue →</button>'))}
function roll(){if(s.lastRoll)return;move(1+Math.floor(Math.random()*10),1+Math.floor(Math.random()*6))}
function move(a,b){let msg;if(a===b){if((s.progress[s.prompt]||0)<3)msg="Doubles. Remain on Prompt "+s.prompt+" and advance to its next Stage.";else msg="Doubles, but all three Stages here are complete. Choose one Prompt forward or backward."}else{const d=Math.abs(a-b),dir=b<a?1:-1,target=s.prompt+dir*d,clamped=Math.max(1,Math.min(10,target));s.prompt=clamped;msg=(dir>0?"Move forward ":"Move backward ")+d+" Prompt"+(d===1?"":"s")+". "+(target!==clamped?"This development slice stops at Prompt "+clamped+".":"You arrive at Prompt "+clamped+".")}s.lastRoll={d10:a,d6:b,message:msg};save();render()}
function continueRoll(){if(s.lastRoll&&s.lastRoll.d10===s.lastRoll.d6&&(s.progress[s.prompt]||0)>=3){s.screen="edge";save();render();return}s.lastRoll=null;s.screen="prompt";save();render()}
function edge(){return shell('<div class="eyebrow">Completed Prompt</div><h2>All three Stages are complete.</h2><p>The rules let you move one Prompt forward or backward.</p><button class="btn" onclick="edgeMove(-1)">← Back one</button><button class="btn primary" onclick="edgeMove(1)">Forward one →</button>')}
function edgeMove(n){s.prompt=Math.max(1,Math.min(10,s.prompt+n));s.lastRoll=null;s.screen="prompt";save();render()}
function story(){const marks=s.marks.length;const standing=marks>=10?"Ruined":marks>=7?"Notorious":marks>=4?"Whispered About":"Unblemished";const mems=s.activeMemories||[{title:s.before,experiences:[]}];return shell('<div class="eyebrow">My Season</div><h2>'+esc(s.name||"Your protagonist")+'</h2><div class="statusline"><span>'+esc(s.station||"No station")+'</span><span>'+marks+' Mark'+(marks===1?"":"s")+'</span><span>'+standing+'</span></div><div class="card"><h3>Skills</h3>'+s.skills.map(x=>'<p>'+esc(x)+((s.exhaustedSkills||[]).includes(x)?' <strong>✓ Checked</strong>':' <span class="small">Available</span>')+'</p>').join("")+'<h3>Resources</h3><p>'+s.resources.map(esc).join(" · ")+'</p><h3>Characters</h3><p>'+s.characters.map(esc).join(" · ")+'</p></div><h3>Active Memories</h3>'+mems.map(m=>'<div class="card"><strong>'+esc(m.title)+'</strong><div class="small">'+m.experiences.length+' of 3 Experiences</div>'+m.experiences.map(e=>'<p>'+esc(e.text)+'</p>').join("")+'</div>').join("")+'<h3>Keyword threads</h3><div class="tagrow">'+Object.entries(s.keywords).map(([k,v])=>'<span class="pill seen">'+esc(k)+' · '+v+'</span>').join("")+'</div><h3>Journal</h3>'+(s.journal.length?s.journal.map(j=>'<div class="journal-entry"><div class="small">Prompt '+j.prompt+' · Stage '+j.stage+' · '+j.keywords.map(esc).join(", ")+'</div><strong>'+esc(j.title)+'</strong><p>'+esc(j.text)+'</p></div>').join(""):'<p class="small">Your Season has not yet begun to fill the page.</p>'))}
function dictate(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition,el=document.getElementById("speechStatus");if(!SR){el.textContent="Dictation is not available in this browser. You can keep typing normally.";return}const r=new SR();r.lang="en-GB";r.interimResults=true;r.continuous=false;const base=s.draft.trim();el.textContent="Listening…";r.onresult=e=>{let t="";for(let i=e.resultIndex;i<e.results.length;i++)t+=e.results[i][0].transcript;t=t.trim();if(t)t=t[0].toUpperCase()+t.slice(1);s.draft=(base?base+" ":"")+t;document.getElementById("draft").value=s.draft;save()};r.onerror=e=>el.textContent="Dictation could not start: "+e.error;r.onend=()=>el.textContent=s.draft?"Dictation added. Edit it as normal.":"";try{r.start()}catch{el.textContent="Dictation could not start."}}
function esc(x){return String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function escq(x){return String(x).replace(/\\/g,"\\\\").replace(/'/g,"\\'")}
function render(){let v=s.screen==="welcome"?welcome():s.screen==="create"?create():s.screen==="prompt"?promptView():s.screen==="memory"?memoryView():s.screen==="dice"?dice():s.screen==="edge"?edge():story();app.innerHTML=v}render();