window.REGENCY_PROMPTS=[
{n:1,title:"A Grand Entrance",keywords:["Ballroom","Triumphant","Dancing","Admirer","Gain"],intro:"My dear, the moment has arrived. The carriage door opens, the footman extends his hand, and the chandeliers blaze like a thousand ambitions. Every eye in the ballroom is about to turn toward you. What happens next is not fate; it is performance. A well-executed entrance can secure a Season; a poorly judged one can doom it. I have seen both. I have written about both. You, I suspect, shall provide me with excellent material either way.",stages:[
["The Threshold","The music swells as you pause at the top of the stairs. The ballroom stretches before you like a sea of silk and candlelight. Conversations falter, fans pause mid-flutter, and a hundred faces turn to assess you. You feel the weight of their gaze, and the thrilling possibility of conquest.","Gain 1 Resource (Favour). Check Skill (Grace, Poise, or Charm). On a Failure, gain 1 Mark (Too Dazzling for Decorum; you tried too hard, and they noticed).","What do you do as you enter that wins Favour, or what flourish crosses into too much? Whose reaction do you notice first?"],
["The First Dance","A gentleman steps forward before you have even reached the floor. His smile is confident, his bow impeccable. You recognise him from somewhere: a portrait, a rumour, or perhaps a dream. He offers his hand, and the orchestra strikes up a waltz. The room watches. You must decide: dance with him and invite speculation, or decline and invite gossip.","Create a Character (Your First Partner). Check Skill (Dancing or Poise). On a Success, gain 1 Resource (Admiring Audience). On a Failure, gain 1 Mark (Over-Observed; you are already the subject of whispers).","Who is your First Partner, why do you recognise them, and what happens during the dance that earns admiration or invites whispers?"],
["The Aftermath","The dance ends. Your partner bows, your hand lingers a moment too long in his. Across the room, someone watches with an expression you cannot quite read: admiration, jealousy, or calculation. You have made an impression. Whether it is the one you intended remains to be seen.","Transform Skill (Grace → Presence). Lose 1 Resource (Favour). You may instead refuse the transformation and keep Grace, but gain 1 Mark (Stubborn).","How has the evening changed the way you carry yourself, or why do you refuse to change? Who notices the difference?"]]},
{n:2,title:"The Unexpected Invitation",keywords:["London","Triumphant","Letter-Writing","Patron","Gain"],intro:"An invitation, my dear, is never merely an invitation. It is a test, a trap, or a triumph, and sometimes all three at once.",stages:[
["The Gilt-Edged Card","The card arrives on a silver tray, sealed with wax the colour of blood. The crest is unmistakable: a house of such consequence that even your mother, for all her ambition, dares not dream of it. You are invited to a soirée at the townhouse of the Marchioness of Ashworth.","Gain 1 Resource (Exclusive Invitation). Check Skill (Discretion). On a Failure, gain 1 Mark (Eager Climber).","How do you react when the invitation arrives, and who notices whether you handle the opportunity with discretion or obvious eagerness?"],
["The Grand Soirée","The Marchioness's townhouse blazes with candlelight. She greets you with a smile that does not reach her eyes, a collector appraising a new acquisition.","Check Skill (Wit). On a Success, gain 1 Character (Intrigued Host). On a Failure, gain 1 Mark (Social Misstep).","What does the Marchioness ask you, and what answer makes her interested in you or reveals your social misstep?"],
["The Quiet Word","Later, in a quiet corner, the Marchioness speaks plainly. She has a favour to ask: something small, something discreet, something that will bind you to her.","If you have the Intrigued Host Character, transform them into an Ally and gain 1 Resource (Connection). If you decline, transform them into a Rival instead and gain 1 Mark (Imprudent Refusal).","What favour does the Marchioness ask, and why do you accept or refuse it?"]]},
{n:3,title:"The Morning Call",keywords:["London","Romantic","Gossiping","Confidant","Transform"],intro:"Morning calls are the social equivalent of chess: all strategy, no bloodshed, unless one counts the wounded pride.",stages:[
["The Drawing Room","You arrive at the appointed hour. Your hostess greets you with a smile that does not quite reach her eyes. The conversation begins.","Gain 1 Resource (Moment of Repose). You may remove 1 Mark (Overwrought) if present. Check Skill (Charm or Poise). On a Failure, gain 1 Mark (Awkward Silences).","What small exchange makes this call graceful, awkward, or unexpectedly restful?"],
["The Confidence","Your hostess leans closer. The conversation turns personal, too personal for a first call. You are being tested.","Create a Character (New Confidant, or perhaps a trap). Gain 1 Mark (Over-Familiar if you offer sympathy, or Cold Reserve if you withdraw).","What confidence does your hostess share, and why has she chosen you?"],
["The Farewell","As you take your leave, your hostess presses your hand a moment too long. You have learned something today.","Transform Skill (Empathy → Discernment) if you have it; if not, transform any one Skill. Alternatively, if you choose to share nothing, gain 1 Resource (Quiet Advantage).","What have you learned from the visit?"]]},
{n:4,title:"The Unexpected Dance",keywords:["Ballroom","Romantic","Dancing","Admirer","Gain"],intro:"A waltz, my dear, is the most dangerous form of flirtation. All the intimacy of a confession, none of the clarity.",stages:[
["The Offer","You have been standing by the wall for three dances. Then a stranger appears. He offers his hand as the opening bars of a waltz fill the room.","Create a Character (Unexpected Partner). Check Skill (Grace). On a Failure, gain 1 Mark (Whispered Misstep).","Who is the Unexpected Partner, and why did you hesitate before accepting their hand?"],
["The Waltz","The dance begins. His hand is warm at your waist; his steps are sure. He speaks in low, careful words, not quite flirtation, not quite confession.","Check Skill (Composure). On a Success, create 1 Memory (Shared Pulse of Music, or continue an existing one). On a Failure, gain 1 Mark (Speculation).","What does your partner say during the waltz?"],
["The Final Turn","The waltz ends. There is a moment of silence between you: a question unasked, an answer ungiven.","On a Success, change the Unexpected Partner’s relationship status to Admirer and gain 1 Resource (Devotion). On a Failure, gain 1 Mark (Spurned). Create a Memory.","What question remains unasked when the dance ends?"]]},
{n:5,title:"The Proposal at Dawn",keywords:["Garden","Romantic","Letter-Writing","Admirer","Transform"],intro:"A proposal at dawn is either the height of romance or the depths of desperation, and occasionally both.",stages:[
["The Unexpected Visit","You are walking in the garden before breakfast. Then you hear footsteps: hurried, deliberate, coming toward you.","Check Skill (Composure). On a Success, gain 1 Resource (New Future). On a Failure, gain 1 Mark (Visible Doubt).","Who has come to find you at dawn, and what about their approach makes this feel like a new future or something you cannot quite trust?"],
["The Declaration","He speaks. His words are well-rehearsed, too well-rehearsed, perhaps. He speaks of your beauty, your wit, your suitability.","Gain 1 Mark (Public Expectation). Check Skill (Empathy or Wit). On a Success, gain 1 Resource (Admiring Attention). On a Failure, gain 1 Mark (Protesting Too Much, or Not Enough).","What exactly do they say that reveals their idea of marriage?"],
["The Answer","You must give your answer now, or you must delay. Each choice is a door. Which one will you open?","On a Success, gain 1 Resource (Position or Freedom). On a Failure, gain 1 Mark (Talk of Regret). Create a Memory (Turning Point, or The One That Got Away).","What answer do you give, and why?"]]},
{n:6,title:"The Confession by Firelight",keywords:["Country Estate","Romantic","Gossiping","Confidant","Reveal"],intro:"Firelight, my dear, is the confidant of every indiscretion. It warms the room and loosens the tongue.",stages:[
["The Quiet Evening","The drawing room is quiet. Most of the household has retired, but you and one other remain. The fire crackles and pops.","Gain 1 Resource (Calm). Check Skill (Empathy). On a Failure, gain 1 Mark (Awkward Silence).","Who has remained with you by the fire, and what turns an ordinary conversation into an intimate one?"],
["The Confession","The other person speaks a truth they have been carrying for weeks, months, perhaps years.","Check Skill (Discretion). On a Success, gain 1 Character (Candid Confidant). On a Failure, gain 1 Mark (Flustered).","What truth do they confess, and why now?"],
["The Morning After","The fire dies down. The confession has been made, and you have received it.","On a Success, gain 1 Resource (Quiet Advantage). On a Failure, gain 1 Mark (Guarded Manner). Create a Memory (The Truth Shared, or The Truth Suppressed).","What do you do with what you have learned?"]]},
{n:7,title:"The Candlelight Confession",keywords:["Country Estate","Romantic","Riding","Confidant","Reveal"],intro:"Candlelight, my dear, is the great equaliser. It softens wrinkles, deepens eyes, and makes even the most guarded heart feel vulnerable.",stages:[
["The Late Return","You return from an evening ride later than intended. The others have gone ahead, leaving you and your companion alone beneath a darkening sky.","Gain 1 Resource (Intimate Moment). Check Skill (Empathy). On a Failure, gain 1 Mark (Awkward Parting).","What happened during the late ride that leaves the two of you reluctant to part?"],
["The Spoken Truth","Your companion speaks. The words are careful at first, then tumbling, then raw.","Check Skill (Composure). On a Success, gain 1 Character (Candid Confidant). On a Failure, gain 1 Mark (Flustered Reaction).","What truth does your companion finally speak?"],
["The Morning Reckoning","Dawn arrives. The candles have burned to nothing. You have been given a gift, or a burden.","On a Success, gain 1 Resource (Truth Kept). On a Failure, gain 1 Mark (Guarded Manner). Create a Memory (The Confession That Changed Everything).","What do you do the next morning because of the confession?"]]},
{n:8,title:"The Midnight Serenade",keywords:["Garden","Romantic","Letter-Writing","Admirer","Reveal"],intro:"A serenade beneath a window is the most romantic of gestures and the most dangerous.",stages:[
["The Music Begins","You are preparing for bed when you hear it: a voice, or perhaps a violin, rising from the garden below.","Gain 1 Character (Secret Admirer). Check Skill (Composure). On a Failure, gain 1 Mark (Flustered).","Who is serenading you, and what does the melody mean to you?"],
["The Window","You approach the window. Below, a figure stands in the moonlight, his face half-hidden by shadow.","Gain 1 Mark (Awakened Household). Check Skill (Discretion). On a Success, gain 1 Resource (Unspoken Devotion). On a Failure, gain 1 Mark (Rumour Rekindled).","What do you do at the window, and what passes between you and the figure below?"],
["The Morning After","At dawn, you find a flower on your windowsill. There is no note. There need not be.","On a Success, gain 1 Resource (Unspoken Devotion). On a Failure, gain 1 Mark (Talk of the Household). Create a Memory (Song at the Window).","What do you do with the flower or token at dawn?"]]},
{n:9,title:"The Music Room Encounter",keywords:["Ballroom","Romantic","Dancing","Admirer","Gain"],intro:"The music room is society's most intimate battlefield. The piano is a confessional, the harp a temptation, and the silence between notes a language all its own.",stages:[
["The Accidental Meeting","You slipped away from the ballroom seeking solitude. What you found was company. In the adjoining music room, a figure stands by the pianoforte.","Check Skill (Composure). On a Success, gain 1 Resource (Controlled Poise). On a Failure, gain 1 Mark (Flushed Cheeks).","Who is waiting in the music room, and what unresolved history stands between you?"],
["The Shared Melody","Without words, you find yourself at the instrument. Fingers brush the keys, and perhaps each other.","Gain 1 Character (Rekindled Flame). Gain 1 Mark (Unwise Intimacy, or Cold Reserve, depending on your choices).","What melody do you both remember, and what old moment returns with it?"],
["The Interruption","The door opens. Someone enters: a servant, a guest, a chaperone. The spell is broken.","On a Success, gain 1 Skill (Discretion). On a Failure, gain 1 Mark (Rumour Rekindled). Create a Memory (The Music Room, and What Was Played).","Who interrupts you, and what do they think they have seen?"]]},
{n:10,title:"The Balcony Encounter",keywords:["London","Romantic","Gossiping","Confidant","Reveal"],intro:"Night air, my dear, is the accomplice of every indiscretion. It cools the skin and warms the heart; it loosens tongues and lowers defences.",stages:[
["The Escape","The ballroom is too loud, too bright, too full of expectation. You slip through the French doors onto the balcony, seeking a moment of silence.","Gain 1 Resource (Moment of Calm). Check Skill (Discretion). On a Failure, gain 1 Mark (Noticeably Fleeing).","Why did you need to escape the ballroom, and who follows you outside?"],
["The Conversation","Your companion steps beside you, leaning on the railing. The city glows below, a sea of lights and secrets.","Gain 1 Character (Moonlit Confidant). Check Skill (Composure). On a Failure, gain 1 Mark (Too Close).","What confidence, confession, or challenge does your companion offer?"],
["The Witness","A curtain stirs behind you. A face appears briefly in the window, or perhaps it was only the wind.","On a Success, gain 1 Skill (Discretion). On a Failure, gain 1 Mark (Rumour of Impropriety). Create a Memory (Night Air and Confessions).","Who might have witnessed the encounter, and what version of the balcony scene survives afterward?"]]}
];